[package]
name = "talos-pilot-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Native egui desktop interface for talos-pilot"

[dependencies]
talos-pilot-core.workspace = true
talos-rs.workspace = true

# Desktop UI
eframe.workspace = true
rfd.workspace = true

# Async backend execution
tokio.workspace = true

# Error handling
color-eyre.workspace = true
